apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  selector:
    matchLabels:
      app: user-profile-app
  template:
    metadata:
      labels:
        app: user-profile-app
    spec:
      containers:
      - name: user-profile-app
        image: "registryezg2364.azurecr.io/userprofile:latest"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-db-secret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-db-secret
                key: SQL_PASSWORD
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sql-db-secret
                key: SQL_DBNAME
          - name: database_url
            valueFrom:
              configMapKeyRef:
                name: node-configmap
                key: database_url

---
  apiVersion: v1
  kind: Service
  metadata:
    name: user-profile-svc
  spec:
    type: ClusterIP
    selector:
      app: user-profile-app
    ports:
    - port: 80
      targetPort: 80
     
