apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
spec:
  selector:
    matchLabels:
      app: tripviewer-app
  template:
    metadata:
      labels:
        app: tripviewer-app
    spec:
      containers:
      - name: tripviewer-app
        image: "registryezg2364.azurecr.io/tripviewer:latest"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-db-secret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-db-secret
                key: SQL_PASSWORD
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sql-db-secret
                key: SQL_DBNAME
          - name: database_url
            valueFrom:
              configMapKeyRef:
                name: node-configmap
                key: database_url
          - name: USERPROFILE_API_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: node-configmap
                key: user_profile_api
          - name: TRIPS_API_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: node-configmap
                key: trip_service_url
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-svc
spec:
  type: LoadBalancer
  selector:
    app: tripviewer-app
  ports:
  - port: 80
    targetPort: 80