apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  selector:
    matchLabels:
      app: user-java-app
  template:
    metadata:
      labels:
        app: user-java-app
    spec:
      containers:
      - name: user-java-app
        image: "registryezg2364.azurecr.io/user-java:latest"
        #resources:
          #limits:
            #memory: "128Mi"
            #cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-db-secret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-db-secret
                key: SQL_PASSWORD
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sql-db-secret
                key: SQL_DBNAME
          - name: database_url
            valueFrom:
              configMapKeyRef:
                name: node-configmap
                key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
spec:
  type: LoadBalancer
  clusterIP: 10.0.24.220
  selector:
    app: user-java-app
  ports:
  - port: 80
    targetPort: 80
          
