apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-user
  namespace: api
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "1197b897-35de-481d-a57f-57bbfa40e26f"